### ISSUE TITLE
data duplication

### ISSUE THREAD

**Issue by liubiantao** [happlebao/rank#3]
![image](https://user-images.githubusercontent.com/3268218/33646940-41e4f9fc-da8d-11e7-8222-46cc9f9cf488.png)

**Comment by bao-work** [comment]
fixed with https://github.com/happlebao/rank/commit/d4322b579ff9b62ec9cbfa81f159691c94b31e01

**Comment by happlebao** [comment]
fixed in https://github.com/happlebao/rank/commit/d4322b579ff9b62ec9cbfa81f159691c94b31e01
