### ISSUE TITLE
建议: 按分类排序以及增加一个新的影响力分类

### ISSUE THREAD

**Issue by liubiantao** [happlebao/rank#4]
1. 可以选择排序方式: 
![image](https://user-images.githubusercontent.com/3268218/33647140-5254d8a6-da8e-11e7-9e8e-48c14b60d61c.png)

2. 影响力
根据 Contributed Star, Followers 等多维度信息, 综合计算出一个影响力分类

**Comment by happlebao** [comment]
会有单独的语言排名。followers 不考虑。这是代码贡献排行榜。
